### ISSUE TITLE
Can't use iwpriv to set network type

### ISSUE THREAD

**Issue by jsantala** [Vonger/vocore2#1]
root@tolppa00E030-00_126:/# iwpriv ra0 set NetworkType=Adhoc
Interface doesn't accept private ioctl...
set (8BE2): Network is down
root@tolppa00E030-00_126:/# ifconfig ra0 up
[  153.086173] efuse_probe: efuse = 10000002
[  153.269593] tssi_1_target_pwr_g_band = 35
[  158.727698] <==== rt28xx_init, Status=0
root@tolppa00E030-00_126:/# iwpriv ra0 set NetworkType=Adhoc
Interface doesn't accept private ioctl...
set (8BE2): Invalid argument

OpenWRT commit 3b6f865

**Comment by Vonger** [comment]
i see :) looks like some code is missing.

**Comment by Vonger** [comment]
Currently driver do not support Adhoc...
