### ISSUE TITLE
SDHCI not found

### ISSUE THREAD

**Issue by james-tate** [Vonger/vocore2#10]
I am getting the following error when building "Error: ../dts/VOCORE2.dts:114.2-3 label or path, 'sdhci', not found". 

I have tried enabling both  kmod-sdhci and kmod-sdhci-mt7620. What other dependencies are needed?

/home/cross/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7628/linux-3.18.29/scripts/dtc/dtc -O dtb -o /home/cross/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7628/VOCORE2.dtb ../dts/VOCORE2.dts
Error: ../dts/VOCORE2.dts:114.2-3 label or path, 'sdhci', not found
FATAL ERROR: Syntax error parsing input tree
Makefile:1077: recipe for target 'install' failed
make[5]: *** [install] Error 1
make[5]: Leaving directory '/home/cross/openwrt/target/linux/ramips/image'
Makefile:26: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/home/cross/openwrt/target/linux/ramips'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/cross/openwrt/target/linux'
target/Makefile:21: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/cross/openwrt'
target/Makefile:17: recipe for target '/home/cross/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.target_install' failed
make[1]: *** [/home/cross/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/cross/openwrt'
Build failed - please re-run with -j1 to see the real error message
/home/cross/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by Vonger** [comment]
which version of openwrt you are using?
I find similar issue(not same, compile no problem), because openwrt update its sdhci driver.

**Comment by james-tate** [comment]
Looks like in the newest openwrt version this is corrected. I was patching this driver into the openwrt source  from http://vonger.cn/misc/vocore2/openwrt.tar.bz2.

**Comment by james-tate** [comment]
I do have a new problem with the current openwrt build for vocore2. I am using current https://github.com/openwrt/openwrt. The ttyS2 console stops after a few seconds (see behavior below). If I ssh in and try "echo hello >> /dev/ttyS2" I get nothing while connected to UART. Using the precompiled upgrade this works fine. I have peeked at the .dts files and I don't spot a problem right away. Any ideas?

---------------------------------------------------------------------------------------------------------
*** Warning - bad CRC, using default environment

============================================
Ralink UBoot Version: 4.3.0.0
--------------------------------------------
ASIC 7628_MP (Port5<->None)
DRAM component: 1024 Mbits DDR, width 16
DRAM bus: 16 bit
Total memory: 128 MBytes
Flash component: SPI Flash
Date:Jun 25 2016  Time:22:54:33
============================================
icache: sets:512, ways:4, linesz:32 ,total:65536
dcache: sets:256, ways:4, linesz:32 ,total:32768
RESET MT7628 PHY!!!!!!
Please choose the operation:
   0: Load system code then write to Flash via SERIAL.
   1: Load system code to SDRAM via TFTP.
   2: Load system code then write to Flash via TFTP.
   3: Boot system code via Flash (default).
   4: Entr boot command line interface.
   5: Load system code then write to Flash via USB Storage.
   7: Load Boot Loader code then write to Flash via Serial.
   8: Start Web Server to load system code.
   9: Load Boot Loader code then write to Flash via TFTP.
gpio trigger enabled
GPIO 46 used to trigger webpage
Hold button for between 3 seconds and 6 seconds
        then release to trigger webpage to load image
Hold button for between 6 seconds and 9 seconds
        then release to trigger loading image from USBSTORAGE
GPIO 46 is low                                                                                                                                  0

3: System Boot system code via Flash.
## Booting image at bc050000 ...
   Image Name:   MIPS OpenWrt Linux-4.14.66
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    1545423 Bytes =  1.5 MB
   Load Address: 80000000
   Entry Point:  80000000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
No initrd
## Transferring control to Linux (at address 80000000) ...
## Giving linux memsize in MB, 128

Starting kernel ...

[    0.000000] Linux version 4.14.66 (cross@cross) (gcc version 7.3.0 (OpenWrt GCC 7.3.0 r7946-2c01425)) #0 Sun Aug 26 16:24:02 2018
[    0.000000] Board has DDR2
[    0.000000] Analog PMU set to hw control
[    0.000000] Digital PMU set to hw control
[    0.000000] SoC Type: MediaTek MT7628AN ver:1 eco:2
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019655 (MIPS 24KEc)
[    0.000000] MIPS: machine is VoCore2
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] random: get_random_bytes called from start_kernel+0x8c/0x474 with crng_init=0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32512
[    0.000000] Kernel command line: console=ttyS2,115200 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=00040001
[    0.000000] Readback ErrCtl register=00040001
[    0.000000] Memory: 124836K/131072K available (3575K kernel code, 169K rwdata, 836K rodata, 212K init, 208K bss, 6236K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 256
[    0.000000] intc: using register map from devicetree
[    0.000000] CPU Clock: 580MHz
[    0.000000] timer_probe: no matching timers found
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6590553264 ns
[    0.000009] sched_clock: 32 bits at 290MHz, resolution 3ns, wraps every 7405115902ns
[    0.007536] Calibrating delay loop... 385.84 BogoMIPS (lpj=1929216)
[    0.073505] pid_max: default: 32768 minimum: 301
[    0.078183] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.084536] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.096887] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.106377] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.112324] pinctrl core: initialized pinctrl subsystem
[    0.117898] NET: Registered protocol family 16
[    0.148341] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.153936] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.159568] mt7621_gpio 10000600.gpio: registering 32 gpios
[    0.169225] clocksource: Switched to clocksource MIPS
[    0.175282] NET: Registered protocol family 2
[    0.180340] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.187030] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.193221] TCP: Hash tables configured (established 1024 bind 1024)
[    0.199481] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.205085] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.211432] NET: Registered protocol family 1
[    0.218917] Crashlog allocated RAM at address 0x3f00000
[    0.225512] workingset: timestamp_bits=30 max_order=15 bucket_order=0
[    0.237363] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.242990] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.262131] io scheduler noop registered
[    0.265861] io scheduler deadline registered (default)
[    0.271707] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    0.278973] 10000c00.uartlite: ttyS0 at MMIO 0x10000c00 (irq = 28, base_baud = 2500000) is a 16550A
[    0.288374] 10000d00.uart1: ttyS1 at MMIO 0x10000d00 (irq = 29, base_baud = 2500000) is a 16550A
[    0.297481] 10000e00.uart2: ttyS2 at MMIO 0x10000e00 (irq = 30, base_baud = 2500000) is a 16550A
[    0.306014] console [ttyS2] enabled
[    0.306014] console [ttyS2] enabled
[    0.313010] bootconsole [early0] disabled
[    0.313010] bootconsole [early0] disabled
[    0.321630] cacheinfo: Failed to find cpu0 device node
[    0.326842] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.333815] spi-mt7621 10000b00.spi: sys_freq: 193333333
[    0.346435] m25p80 spi0.0: gd25q128 (16384 Kbytes)
[    0.351410] 4 fixed-partitions partitions found on MTD device spi0.0
[    0.357851] Creating 4 MTD partitions on "spi0.0":
[    0.362731] 0x000000000000-0x000000030000 : "u-boot"
[    0.368694] 0x000000030000-0x000000040000 : "u-boot-env"
[    0.374990] 0x000000040000-0x000000050000 : "factory"
[    0.381048] 0x000000050000-0x000001000000 : "firmware"
[    0.456562] 2 uimage-fw partitions found on MTD device firmware
[    0.462613] 0x000000050000-0x0000001c950f : "kernel"
[    0.468535] 0x0000001c950f-0x000001000000 : "rootfs"
[    0.474416] mtd: device 5 (rootfs) set to be root filesystem
[    0.481717] 1 squashfs-split partitions found on MTD device rootfs
[    0.488006] 0x0000003b0000-0x000001000000 : "rootfs_data"
[    0.495196] libphy: Fixed MDIO Bus: probed
[    0.510829] rt3050-esw 10110000.esw: link changed 0x00
[    0.517723] mtk_soc_eth 10100000.ethernet eth0: mediatek frame engine at 0xb0100000, irq 5
[    0.527950] NET: Registered protocol family 10
[    0.536564] Segment Routing with IPv6
[    0.540480] NET: Registered protocol family 17
[    0.545042] 8021q: 802.1Q VLAN Support v1.8
[    0.559215] VFS: Mounted root (squashfs filesystem) readonly on device 31:5.
[    0.567583] Freeing unused kernel memory: 212K
[    0.572122] This architecture does not have kernel memory protection.
[    1.752450] init: Console is alive
[    1.756131] init: - watchdog -
[    2.260944] random: fast init done
[    3.040195] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    3.135398] usbcore: registered new interface driver usbfs
[    3.141143] usbcore: registered new interface driver hub
[    3.146636] usbcore: registered new device driver usb
[    3.157367] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    3.165751] ehci-platform: EHCI generic platform driver
[    3.181444] phy phy-10120000.usbphy.0: remote usb device wakeup disabled
[    3.188246] phy phy-10120000.usbphy.0: UTMI 16bit 30MHz
[    3.193572] ehci-platform 101c0000.ehci: EHCI Host Controller
[    3.199454] ehci-platform 101c0000.ehci: new USB bus registered, assigned bus number 1
[    3.207600] ehci-platform 101c0000.ehci: irq 26, io mem 0x101c0000
[    3.239243] ehci-platform 101c0000.ehci: USB 2.0 started, EHCI 1.00
[    3.246598] hub 1-0:1.0: USB hub found
[    3.250858] hub 1-0:1.0: 1 port detected
[    3.258242] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    3.266211] ohci-platform: OHCI generic platform driver
[    3.271851] ohci-platform 101c1000.ohci: Generic Platform OHCI controller
[    3.278765] ohci-platform 101c1000.ohci: new USB bus registered, assigned bus number 2
[    3.286930] ohci-platform 101c1000.ohci: irq 26, io mem 0x101c1000
[    3.364351] hub 2-0:1.0: USB hub found
[    3.368538] hub 2-0:1.0: 1 port detected

**Comment by Vonger** [comment]
I have find this problem, it is openwrt commit 3a8efaef00d6b7317c46fe6b7e923912d8bf3500 broken the sdhci driver, make UART2 can not work properly. I have emailed openwrt but no reply yet. Please also email them to require revert that patch :)

**Comment by james-tate** [comment]
Will do! Thanks for helping track it down.
