### ISSUE TITLE
/etc/config/wireless ignored

### ISSUE THREAD

**Issue by ranlyticsBrad** [Vonger/vocore2#15]
When changing the ssid in the wireless config file, submitting "wifi up", nothing changes. the ssid is always "VoCore2".

Setting encryption is ignored too. it seems it doesn't read this file and uses some other source?

**Comment by Vonger** [comment]
this works pretty well, maybe you missed some compile steps?
or try 20190316.bin or 20190422.bin at http://vonger.cn/misc/vocore2/, that is mine compiled firmware, i tested on 20190316, works.

**Comment by ranlyticsBrad** [comment]
Ok, i see what i did wrong. I didn't run this patch:
patch -p1 < ./package/vocore2/mt7628/openwrt/000-*.patch

Works now after running that. 

Can close this out to user error :+1:
