### ISSUE TITLE
Sta mode is not working

### ISSUE THREAD

**Issue by artificerpi** [Vonger/vocore2#2]
I got following error, which kept outputting in the serial console.
```
[  826.460057] MlmeEnqueueForRecv(): un-recongnized mgmt->subtype=4, STA-xx:xx:xx:xx:xx:xx
[  832.135500] ERROR!!! 
```
vocore2 has connected to the AP, but it seems that the packets cannot be correctly parsed.
Any workaround for STA+AP right now?

**Comment by Vonger** [comment]
no such issue for me, how do you setting up?

**Comment by artificerpi** [comment]
By `Setup AP + STA Mode guide` from http://vocore.io/v2.html, I've tried both compiling from openwrt source codes and flashing firmware http://vonger.cn/misc/vocore2/20170527V.bin, but they all given above error.

**Comment by Vonger** [comment]
try http://vonger.cn/misc/vocore2/20180723V.bin

**Comment by artificerpi** [comment]
Referred to this [issue](https://github.com/respeaker/get_started_with_respeaker/issues/94), I tried to power device with usb charger and solved this issue. Suggest to document the power supply requirements. Thx.
