### ISSUE TITLE
Faster boot to wifi

### ISSUE THREAD

**Issue by dmacattack** [Vonger/vocore2#22]
I really like this work. 
I have tried to optimize the init.d scripts, and the number of kernel modules, but I cannot get the wifi to boot faster than ~24-29s. Is there any suggestions/optimizations that can be implemented ? 

I'm using the "br-wlan/wlan0 ready" as my marker:
[   24.124659] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   24.135589] br-lan: port 2(wlan0) entered blocking state
[   24.141084] br-lan: port 2(wlan0) entered disabled state
[   24.146845] device wlan0 entered promiscuous mode
[   24.164258] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready <----- my visual marker 

Thanks

**Comment by Vonger** [comment]
Currently that part need to boot after network stack, so it is slow, I do not find a good way to boost it.
