### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by wangmoumou123** [Vonger/vocore2#24]
WARNING: Makefile 'package/vocore2/utils/qt5/Makefile' has a build dependency on '+libstdcpp', which does not exist
bash: /root/openwrt/scripts/timestamp.pl: Permission denied
bash: /root/openwrt/scripts/time.pl: Permission denied
target/Makefile:23: recipe for target 'target/linux/prereq' failed
make[3]: *** [target/linux/prereq] Error 126
target/Makefile:17: recipe for target '/root/openwrt/staging_dir/target-mips_24kc_musl/stamp/.target_prereq' failed
make[2]: *** [/root/openwrt/staging_dir/target-mips_24kc_musl/stamp/.target_prereq] Error 2
/root/openwrt/include/toplevel.mk:205: recipe for target 'prereq' failed
make[1]: *** [prereq] Error 2
/root/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by Vonger** [comment]
just select libstdcpp in openwrt menuconfig...
