### ISSUE TITLE
no sound device (22.03.0)

### ISSUE THREAD

**Issue by basiliscos** [Vonger/vocore2#27]
Hi,

I have compiled the openwrt with 

```
CONFIG_PACKAGE_kmod-sdhci-mt7620=y
CONFIG_PACKAGE_kmod-sound-mt7620=y
```

but there are no `/dev/mixer` etc. after reboot. What can be done?

**Comment by newluhux** [comment]
new patch available:

https://github.com/Vonger/vocore2/pull/30

**Comment by qtopie** [comment]
kmod-sound-mt7628 is not found in 22.03 but it's available in 21.02. 

![image](https://user-images.githubusercontent.com/11538418/202886416-a6633861-ade3-4e5f-a356-2d54c8e65549.png)

BTW, I've tried and managed to make audio of my vocore2u work with firmware 21.02.

**Comment by Vonger** [comment]
22.03 is using new kenerl of Linux, it has a weird bug will crash the driver, we are looking into this.

**Comment by basiliscos** [comment]
any news so far?

**Comment by Vonger** [comment]
> any news so far?

works now, apply the 23.05 sound patch
