### ISSUE TITLE
Is this company still in business

### ISSUE THREAD

**Issue by nsmith1024** [Vonger/vocore2#38]
Hello,

Im wondering if this company is still in business. I've sent several emails to the email address listed on their website and i never get a response.

I just want to know if they are still in business before I start designing circuit boards using their VoCore2 module.

Does anybody know if they are still in business?

Thanks

**Comment by Vonger** [comment]
Yes :) just no notify from github to us. Seems like our agent did not get any email from you either, please email to supoprt@vocore.io / sales@vocore.io
