### ISSUE TITLE
trouble with instalation on raspbian

### ISSUE THREAD

**Issue by josipnigojevic** [Vonger/vocore2#39]
So i followed the steps to install the Vocore 2 driver on raspbian, the device used is Raspberry Pi 3 B+, there were no problems during instalation but after i connect the vocore screen and reboot the pi, the screen briefly turns white and then black. what can be done about this?

**Comment by Vonger** [comment]
Please check this tutorial about install VoCore2 screen on RPi https://vonger.cn/?p=15349
