### ISSUE TITLE
compliation errors for mt7628 wifi driver

### ISSUE THREAD

**Issue by sumitmamoria** [Vonger/vocore2#40]
I am trying to compile openwrt v21.02 by following the README. The build fails by throwing this error:

"openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt7628-p4rev-120395/build/mt7628.ko' is missing."

Any ideas ?

**Comment by Vonger** [comment]
This /mt7628-p4rev-120395 is MTK driver, do you compile it successfully?

**Comment by Vonger** [comment]
Open source driver now works well. MTK driver can be unselect.
