### ISSUE TITLE
wifi not working with v19.07

### ISSUE THREAD

**Issue by sumitmamoria** [Vonger/vocore2#41]
After kernel compilation with mt7628 wifi driver, when I try 'wifi' command it show this error:

MCUSysInit: NICLoadFirmware failed, Status[=0x00000001]

Any ideas?

**Comment by Vonger** [comment]
That is MTK driver, your factory setting partition(256byte) is gone. Just copy back the factory partition to the NOR flash at 0x10000, it will back to work
