### ISSUE TITLE
linux-ramips_mt76x8/linux-5.10.184/sound/soc/codecs/snd-soc-es8328.ko' is missing.

### ISSUE THREAD

**Issue by Magical-Lin** [Vonger/vocore2#45]
ERROR: module '/home/ykl/work/2203/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/linux-5.10.184/sound/soc/codecs/snd-soc-es8328.ko' is missing.

**Comment by Vonger** [comment]
Try 23.05 patches.
