### ISSUE TITLE
SDCard support

### ISSUE THREAD

**Issue by ggirou** [Vonger/vocore2#48]
I have VoCore2 Ultimate and I want to extend storage using an SDCard, so I can install large packages like tesseract.

I tried with latest firmware from [Vocore](https://vonger.cn/misc/vocore2/20240316.23062.bin) and the one from [Openwrt](https://openwrt.org/toh/hwdata/vocore/vocore_vocore2) but SDcard doesn't seem to be detected (see dmesg logs attached).

Did I miss something?
Should I build Openwrt myself?

Thanks

[dmesg-openwrt.txt](https://github.com/Vonger/vocore2/files/15298022/dmesg-openwrt.txt)
[dmesg-vocore.txt](https://github.com/Vonger/vocore2/files/15298023/dmesg-vocore.txt)

**Comment by Vonger** [comment]
try this tutorial: https://vonger.cn/?p=14685, normally do not need to compile again, but if some drivers missing that is necessary.
